### PR TITLE
Add Playable Metadata

### PR DESCRIPTION
**Pull request by Alanko5**
If this information is set this way, the information will be visible on other Apple devices.
https://www.imore.com/sites/imore.com/files/styles/xlarge/public/field/image/2017/10/ios-11-control-center-now-playing-scrub-through-tracks-screens-01.jpeg

### CODE REVIEW

**Comment by kingslay** [comment]
I had add seekable 8fdde0730e5f03a633743d1a806b3927c8933ac0.   MPNowPlayingInfoCenter.default() is a sharedInstance. So you modify it anywhere, without having the method setNowPlaingInfo

**Comment by Alanko5** [comment]
@kingslay 
your implementation is incorrect.
You need to update MPNowPlayingInfoPropertyElapsedPlaybackTime every time the time changes, not just when you take  pause.
If the player is paused, you cannot update the time.
I've completed the NowPlayingInfo implementation, look at it now.

**Comment by kingslay** [comment]
why self.setNowPlaingInfo(metadata: nil) when pause

**Comment by Alanko5** [comment]
> self.setNowPlaingInfo(metadata: nil)

only if player stoped, not paused.

**Pull request merged**
